version: 5.0.{build}

image: Visual Studio 2022

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

before_build:
  - nuget restore Source\SVGImage.sln

build:
  project: Source\SVGImage.sln

test: off

artifacts:
  - path: '**\DotNetProjects.SVGImage*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: hXe36dnupGiXmHiZet1HToyPsDny8d6SpKJvmxb/IyYVt9JXrq3bOo9nU5CZ7NKT
  artifact: /.*(\.|\.s)nupkg/
  
  
  
