version: 2.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

before_build:
  - nuget restore
  
build:
  project: SVGImage\SVGImage.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: SVGImage\SVGImage\bin\Debug\DotNetProjects.SVGImage.dll
    name: DotNetProjects.SVGImage.dll
  - path: SVGImage\SVGImage\bin\Debug\DotNetProjects.SVGImage.pdb
    name: DotNetProjects.SVGImage.pdb
  - path: '**\DotNetProjects.SVGImage*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  