# Your GitHub workflow file under .github/workflows/
name: DocFX

on:
  push:
    branches:
      - master
      
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet tool update -g docfx
    - run: docfx Docs/docfx.json

    - name: Upload DocFX packages
      uses: actions/upload-artifact@v3
      with:
        name: docfx_site
        path: ${{ github.workspace }}/Docs/_site
          
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Docs/_site
